---
- name: Install baseline dependencies
  community.general.pacman:
    name:
      - nfs-utils
    state: present

- name: Install DKMS build dependencies
  community.general.pacman:
    name:
      - base-devel
      - dkms
      - linux-headers
    state: present
    update_cache: true

- name: Download i915 sriov kmod archive
  ansible.builtin.unarchive:
    src: https://github.com/strongtz/i915-sriov-dkms/archive/refs/heads/kernel-v7.0.tar.gz
    dest: /tmp
    remote_src: true

- name: Read i915 DKMS module version
  ansible.builtin.command:
    cmd: awk -F= '/^PACKAGE_VERSION=/{gsub(/"/, "", $2); print $2}' /tmp/i915-sriov-dkms-kernel-v7.0/dkms.conf
  changed_when: false
  register: i915_sriov_dkms_version

- name: Add i915 DKMS module
  ansible.builtin.command:
    cmd: dkms add ./i915-sriov-dkms-kernel-v7.0
    chdir: /tmp
    creates: /var/lib/dkms/i915-sriov-dkms/{{ i915_sriov_dkms_version.stdout }}/source

- name: Build and install i915 DKMS module
  ansible.builtin.command:
    cmd: dkms install i915-sriov-dkms/{{ i915_sriov_dkms_version.stdout }}
    creates: /var/lib/dkms/i915-sriov-dkms/{{ i915_sriov_dkms_version.stdout }}/{{ ansible_facts['kernel'] }}/x86_64/module/i915.ko.zst

- name: Set i915 sriov kernel arguments
  ansible.builtin.lineinfile:
    path: /boot/grub/grub.cfg
    regexp: '^(    linux /boot/vmlinuz-linux root=UUID=.* rw)(?!.* intel_iommu=on i915.enable_guc=3 module_blacklist=xe)(.*)$'
    line: '\1 intel_iommu=on i915.enable_guc=3 module_blacklist=xe\2'
    backrefs: true

- name: Regenerate initramfs after DKMS install
  ansible.builtin.command: mkinitcpio -P
