---
- name: Create elrepo-kernel YUM repository
  ansible.builtin.yum_repository:
    name: elrepo-kernel
    description: elrepo-kernel
    baseurl: http://elrepo.org/linux/kernel/el10/x86_64/
    gpgcheck: no
    enabled: yes

- name: Install new kernel
  ansible.builtin.dnf:
    name: "kernel-ml"
    enablerepo: elrepo-kernel
    state: latest
    lock_timeout: 60

- name: Change grub default kernel
  ansible.builtin.command: /usr/sbin/grubby --set-default-index=0
